In [ ]:
import numpy as np
rows, cols = 20000, 10000
data = np.random.randint(0, 100, size=(rows, cols))
np.savetxt("random_matrix.csv", data, delimiter=",", fmt="%d")
print("Data file created successfully!")

Data file created successfully!


In [ ]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
for i in range(1, mat.shape[0]):
    mat[0] += mat[i]
print("Updated Matrix:\n", mat)

Updated Matrix:
 [[12 15 18]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
from collections import defaultdict
data = [1, 2, 2, 3, 1, 4, 3, 2, 1]
groups = defaultdict(list)
for x in data:
    groups[x].append(x)
matrix = list(groups.values())
print("Grouped Matrix:")
for row in matrix:
    print(row)

Grouped Matrix:
[1, 1, 1]
[2, 2, 2]
[3, 3]
[4]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
add_result = A + B
sub_result = A - B
print("Addition:\n", add_result)
print("Subtraction:\n", sub_result)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]


In [ ]:
n = 4
mat = np.zeros((n, n), dtype=int)
num = 2
for i in range(n):
    for j in range(n):
        mat[i, j] = num
        num += 2
print("Generated Matrix:\n", mat)

Generated Matrix:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [ ]:
matrix = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)
row_sums = [sum(row) for row in matrix]
print("Row-wise sums:", row_sums)

Row-wise sums: [6, 15, 24]
